version: "3"

services:
  app:
    image: 568252011159.dkr.ecr.ap-northeast-1.amazonaws.com/go-basic:1.15
    tty: true
    volumes:
      - ./:/go/src/github.com/hgkcho/cobraReleaser
    working_dir: /go/src/github.com/hgkcho/cobraReleaser
